<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>skillsjars-example-code-assistant</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <name>SkillsJars Example Code Assistant</name>

    <dependencies>
        <dependency>
            <groupId>com.skillsjars</groupId>
            <artifactId>anthropics__skills__pdf</artifactId>
            <version>2026_02_06-1ed29a0</version>
        </dependency>
        <dependency>
            <groupId>com.skillsjars</groupId>
            <artifactId>sivaprasadreddy__sivalabs-agent-skills__spring-boot</artifactId>
            <version>2026_02_23-dba3310</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.skillsjars</groupId>
                <artifactId>maven-plugin</artifactId>
                <version>0.0.2-SNAPSHOT</version>
            </plugin>
        </plugins>
    </build>
</project>
